[package]
name = "jo12bar_os"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

default-run = "jo12bar_os"

[workspace]
members = ["kernel"]

[dependencies]
ovmf-prebuilt = "0.1.0-alpha.1"

[build-dependencies]
bootloader = "0.11.7"
kernel = { path = "kernel", artifact = "bin", target = "x86_64-unknown-none" }
